### PR TITLE
Shape color change in draw.io interface fix

### PR DESCRIPTION
**Pull request by rsarvas**
I made some slight changes to generated XML data to get the shape fill colors editable in in the draw.io interface. Comments added in the code. The actual fix is a bit of a hack, but it works.

### CODE REVIEW

**Comment by webketje** [comment]
Hey I only see this now. This looks pretty solid, thanks. Also for the explanatory comments! Can't wait to give it a testrun

**Comment by rsarvas** [comment]
No worries. Let me know if you have any questions about this. I love to do
crazy stuff with code and Draw.io

Rick

**Comment by webketje** [comment]
This worked like a charm, thanks a lot. I will also update the relevant sections of the README and do a new release ASAP

**Comment by webketje** [comment]
I was this happy with the change
fontawesome-diorama

**Pull request merged**
